---
name: Static analysis
on: [push, pull_request]
permissions: read-all
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6.1.1
        with:
          version: v1.60.1
          args: --config tools/.golangci.yaml
      - run: |
          set -euo pipefail

          make verify
      - run: |
          set -euo pipefail

          make fmt

          DIFF=$(git status --porcelain)

          if [ -n "$DIFF" ]; then
            echo "These files were modified:"
            echo
            echo "$DIFF"
            echo
            exit 1
          fi
